[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
parser = { path = "../parser" }
lexer = { path = "../lexer" }
dfbin = { path = "K:/Programming/GitHub/dfasm/dfbin"}
thiserror = "1.0.65"